name: main

on:
  push:
    branches:
      - "master"
    tags:
      - "*"
  pull_request:
    branches:
      - "master"
    types: [opened, synchronize]

permissions:
  contents: read
  packages: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Code format check by Spotless
        run: ./gradlew spotlessCheck

      - name: Build Gem
        run: ./gradlew gem

      - name: Set up JRuby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: jruby

      - name: Publish to GPR
        if: startsWith( github.ref, 'refs/tags/' )
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} ./pkg/*.gem
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
          OWNER: ${{ github.repository_owner }}
